name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run action
        uses: ./

      - name: Run action with version
        uses: ./
        with:
          version: 2.3.4
